fixed return value of a edge, for non line egdes as arcs
pyansys/pyaedt pull request #1306
Opened 2022-06-20 07:59 UTC by Marc-Vieweger

routine now supports arcs and splines

old version was only valid for lines. For an arc or spline, the length of the edge is not the distance between to vertecies.

2022-06-20 14:26 UTC, maxcapodi78 approved these changes
LGTM

2022-06-20 14:57 UTC, maxcapodi78 commented
@Marc-Vieweger can you contact me on Teams? I'd like to know you as you are first time runner

2022-06-24 09:03 UTC, maxcapodi78 requested changes
I think a merge from main is needed before going on

2022-06-27 07:48 UTC, maxcapodi78 commented
@Marc-Vieweger please merge from main and resolve conflict and push again. it should then pass the tests

2022-08-22 17:40 UTC, MaxJPRey commented
@Marc-Vieweger This is now part of the code (encapsulated in a `try/catch`)
See:

```
try:
    return float(self.oeditor.GetEdgeLength(self.id))
except:
    return False
```

2022-08-22 17:49 UTC, closed without merging