Assign current density and current density terminal implementation - Maxwell2D/3D
pyansys/pyaedt pull request #1598
Opened 2022-08-25 14:02 UTC by gmalinve

2022-08-25 17:46 UTC, maxcapodi78 requested changes
We need to review it. We need to use Boundary Class instead of creating array in this way.

2022-08-25 18:11 UTC, MaxJPRey commented on pyaedt/maxwell.py
> +            Possible values can be 'Cartesian', 'Cylindrical', 'Spherical'.
```suggestion
            Possible values can be 'Cartesian', 'Cylindrical', and 'Spherical'.
```

2022-08-25 18:13 UTC, MaxJPRey commented on pyaedt/maxwell.py
> +            Default value is 'Cartesian'.
```suggestion
            Possible values can be ``"Cartesian"``, ``"Cylindrical"``, and ``"Spherical"``.
            Default value is ``"Cartesian"``.
```

2022-08-29 15:59 UTC, maxcapodi78 approved these changes

2022-08-29 15:59 UTC, merged