Update padstack.py
pyansys/PyAEDT pull request #197
Opened 2021-06-30 21:16 UTC by PipKat

2021-06-30 21:18 UTC, PipKat commented on pyaedt/edb_core/padstack.py
> +        """Retrive all padstacks.
```suggestion
        """Retrieve all padstacks.
```

2021-06-30 21:19 UTC, PipKat commented on pyaedt/edb_core/padstack.py
> +            Rotation of the padstack in degress. The default
```suggestion
            Rotation of the padstack in degrees. The default  
```

2021-06-30 21:20 UTC, PipKat commented on pyaedt/edb_core/padstack.py
> +This module contains the ``EdbPadstack`` class.
```suggestion
This module contains the ``EdbPadstacks`` class.
```

2021-07-01 05:24 UTC, akaszynski commented on pyaedt/edb_core/padstack.py
>      @property
```suggestion
        return self.parent.core_stackup.stackup_layers

    @property
```

2021-07-01 05:24 UTC, akaszynski commented on pyaedt/edb_core/padstack.py
>                         via_name="", rotation = 0, fromlayer = None, tolayer = None, solderlayer=None):
```suggestion
                       via_name="", rotation=0, fromlayer=None, tolayer=None, solderlayer=None):
```

2021-07-01 05:25 UTC, akaszynski commented on pyaedt/edb_core/padstack.py
> +        rotation :
```suggestion
        rotation : float, optional
```

2021-07-01 05:26 UTC, akaszynski commented on pyaedt/edb_core/padstack.py
> +        position :
@maxcapodi78, could you please help fill in the descriptions of these parameters?

2021-07-01 05:27 UTC, akaszynski requested changes
Need massimo to fill out the parameter descriptions.

2021-07-01 07:23 UTC, maxcapodi78 requested changes

2021-07-01 07:23 UTC, maxcapodi78 commented on pyaedt/edb_core/padstack.py
> +        position :
```suggestion
        position : list
            list of [x,y] position where the via will be placed. x, y are float
```

2021-07-01 15:10 UTC, PipKat commented on pyaedt/edb_core/padstack.py
> +        """Retrieve all padstacks.
```suggestion
        """List of padstacks via padstack definitions.
```

2021-07-02 06:08 UTC, akaszynski approved these changes
Thanks for fixing.  Hope you're fine with me merging this.

2021-07-02 06:08 UTC, akaszynski approved these changes

2021-07-02 06:09 UTC, merged