distutils-compatible setup script
pyansys/PyAEDT pull request #249
Opened 2021-07-09 18:00 UTC by isaacansys

Add a new distutils-compatible setup script to facilitate installation of PyAEDT with the AEDT-provided IronPython installation.  Move common setup data into a shared file so it has a single source location.  In local testing I confirmed that CPython 3.8 and IronPython from AEDT can run the install command of the setup.py and setup-distutils.py scripts, respectively.

2021-07-10 00:45 UTC, akaszynski commented
Can't confirm this works on IronPython, but CI for CPython reports the following error:
```
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-bz16r2y4/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-bz16r2y4/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-e34u70re
         cwd: /tmp/pip-req-build-bz16r2y4/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-bz16r2y4/setup.py", line 4, in <module>
        from _setup_common import name, version, author, maintainer, maintainer_email, description, long_description, packages, data_files, license, classifiers
    ModuleNotFoundError: No module named '_setup_common'
```

Reproduce this error within CPython with:
```
python setup.py sdist
pip install dist/pyaedt-0.3.dev0.tar.gz
```

2021-07-10 00:45 UTC, akaszynski requested changes
Please fix the CPython install from the source distribution.

2021-07-10 01:15 UTC, akaszynski commented
Turns out the trick is to include `_setup_common.py` in `MANIFEST.in`.  Normally, only *.py source files within package directories are picked by setup.py when building `sdist`.  This way, we force it to be included with the source distribution.

2021-07-10 15:23 UTC, akaszynski approved these changes
@maxcapodi78, I'd like you to validate this prior to merge or to review the PR as well, but it works correctly now for CPython with the `manifest.in`.

2021-07-12 15:05 UTC, isaacansys commented
@akaszynski thanks for fixing this up.  @maxcapodi78 and I had discussed the need to add setup-distutils to the data_files but I missed adding the base _setup_common.py

2021-07-12 15:19 UTC, maxcapodi78 commented
I agree. This is an important point to get Linux users a smart way to install and use pyaedt.

2021-07-12 18:23 UTC, merged